#!/bin/bash
# Insert CSS
sed -i 's/<\/style>/        .header-right-actions { position: absolute; right: 16px; top: 50%; transform: translateY(-50%); display: flex; align-items: center; gap: 12px; }\n        .action-icon-btn { border: none; background: transparent; font-size: 18px; color: #333; cursor: pointer; padding: 4px; }\n        \/* 弹窗样式 *\/ \n        .settings-modal { display: none; position: fixed; top: 0; left: 50%; transform: translateX(-50%); width: 100%; max-width: 480px; height: 100%; z-index: 1000; background: rgba(0, 0, 0, 0.5); justify-content: flex-end; flex-direction: column; }\n        .settings-modal .modal-body { position: relative; background: #fff; border-top-left-radius: 20px; border-top-right-radius: 20px; padding: 12px 20px 24px 20px; box-shadow: 0 -4px 20px rgba(0,0,0,0.15); transform: translateY(100%); transition: transform 0.3s ease-out; display: flex; flex-direction: column; z-index: 1001; }\n        .switch { position: relative; display: inline-block; width: 44px; height: 24px; }\n        .switch input { opacity: 0; width: 0; height: 0; }\n        .slider { position: absolute; cursor: pointer; top: 0; left: 0; right: 0; bottom: 0; background-color: #ccc; transition: .4s; border-radius: 24px; }\n        .slider:before { position: absolute; content: ""; height: 18px; width: 18px; left: 3px; bottom: 3px; background-color: white; transition: .4s; border-radius: 50%; }\n        input:checked + .slider { background-color: #ff4d4f; }\n        input:checked + .slider:before { transform: translateX(20px); }\n<\/style>/' ./mobile/cuotiben.html

# Insert Header HTML
sed -i 's/<div class="nav-tabs">/<div class="header-right-actions">\n            <button class="action-icon-btn" onclick="showSettingsModal()"><i class="fas fa-cog"><\/i><\/button>\n            <button class="action-icon-btn" onclick="showPcToast('\''导出成功'\'')"><i class="fas fa-file-export"><\/i><\/button>\n        <\/div>\n        <div class="nav-tabs">/' ./mobile/cuotiben.html

# Insert Modal HTML
sed -i 's/<\/body>/    <!-- 设置弹窗 -->\n    <div id="settings-modal" class="settings-modal">\n        <div class="modal-backdrop" onclick="closeSettingsModal()" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"><\/div>\n        <div class="modal-body">\n            <div style="width: 36px; height: 5px; background: #e0e0e0; border-radius: 3px; margin: 0 auto 16px auto; flex-shrink: 0;"><\/div>\n            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; padding-bottom: 12px; border-bottom: 1px solid #f0f0f0;">\n                <span style="font-size: 16px; font-weight: 600; color: #333;">设置<\/span>\n                <i class="fas fa-times" onclick="closeSettingsModal()" style="color: #999; font-size: 16px; cursor: pointer; padding: 4px;"><\/i>\n            <\/div>\n            <div style="display: flex; justify-content: space-between; align-items: center; padding: 12px 0;">\n                <span style="font-size: 15px; color: #333;">答对错题自动移除<\/span>\n                <label class="switch">\n                    <input type="checkbox" id="auto-remove-switch">\n                    <span class="slider"><\/span>\n                <\/label>\n            <\/div>\n        <\/div>\n    <\/div>\n    <script>\n        function showSettingsModal() {\n            const modal = document.getElementById('\''settings-modal'\'');\n            const body = modal.querySelector('\''.modal-body'\'');\n            modal.style.display = '\''flex'\'';\n            setTimeout(() => {\n                body.style.transform = '\''translateY(0)'\'';\n            }, 10);\n        }\n        function closeSettingsModal() {\n            const modal = document.getElementById('\''settings-modal'\'');\n            const body = modal.querySelector('\''.modal-body'\'');\n            body.style.transform = '\''translateY(100%)'\'';\n            setTimeout(() => {\n                modal.style.display = '\''none'\'';\n            }, 300);\n        }\n    <\/script>\n<\/body>/' ./mobile/cuotiben.html
